- name: "Install Apache2 and PHP on each host"
  hosts: "*"
  vars_files:
    - ../track.yaml
  tasks:
    - name: "Load flags"
      loop: "{{ flags }}"
      vars:
        key: "{{ (item.tags).discourse }}"
        value: "{{ item.flag }}"
      ansible.builtin.set_fact:
        track_flags: "{{ track_flags | default({}) | combine({key: value}) }}"

    # Removed APT commands to avoid workflow failure
    # - name: Initial System Upgrade
    #   ansible.builtin.apt:
    #     update_cache: true
    #     install_recommends: false
    #     upgrade: full

    # - name: Install PHP and Apache2
    #   ansible.builtin.apt:
    #     name:
    #       - php
    #       - apache2
    #       - libapache2-mod-php
    #     state: present

    # - name: Remove default file "/var/www/html/index.html"
    #   ansible.builtin.file:
    #     path: "/var/www/html/index.html"
    #     state: absent

    - name: Copy the main site file (index.php)
      ansible.builtin.template:
        src: challenge/index.php
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'

    # - name: Restart Apache2 on failure
    #   ansible.builtin.replace:
    #     path: "/lib/systemd/system/apache2.service"
    #     regexp: 'Restart=.+$'
    #     replace: 'Restart=on-failure'

    # - name: Restart Apache2
    #   ansible.builtin.service:
    #     name: apache2
    #     state: restarted
