---
- name: Delete the unattend file
  ansible.windows.win_file:
    name: C:\windows\system32\sysprep\unattend.xml
    state: absent
  when: not (nsec_post_deployment | bool)

- name: Delete the unattend panther file
  ansible.windows.win_file:
    name: C:\windows\panther\unattend.xml
    state: absent
  when: not (nsec_post_deployment | bool)

- name: Disable windows defender sending sample
  ansible.windows.win_shell: Set-MpPreference -SubmitSamplesConsent 2
  when: not (nsec_post_deployment | bool)

- name: Disable Defender via registry
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
    name: DisableAntiSpyware
    data: 1
    type: dword
  when: not (nsec_post_deployment | bool)

- name: Change the local Administrator password
  ansible.windows.win_command: |
    powershell -Command
      net user Administrator {{ local_admin_password }};
      Set-LocalUser -Name 'Administrator' -PasswordNeverExpires $true;
  when: nsec_post_deployment | bool

# If using incus-windows, there is a default `admin` user that is created.
- name: Remove the local admin user
  ansible.windows.win_command: powershell -Command "net user /delete admin"
  ignore_errors: true
  when: nsec_post_deployment | bool
