- name: "Mock track with build container"
  hosts: all,!build
  vars_files:
    - ../track.yaml
  tasks:
    - name: "Load flags"
      loop: "{{ flags }}"
      vars:
        key: "{{ (item.tags).discourse }}"
        value: "{{ item.flag }}"
      ansible.builtin.set_fact:
        track_flags: "{{ track_flags | default({}) | combine({key: value}) }}"

    - name: Unarchive the content of the build
      ansible.builtin.unarchive:
        src: /tmp/build.tar
        dest: /tmp/
        owner: root
        group: root
        mode: '0755'
