---
- name: Disable Telemetry via group policy
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: AllowTelemetry
    data: 0
    type: dword
  register: _windows_optimize_ret
  until: _windows_optimize_ret is success
  retries: 8
  delay: 15
